- meson.build
It is required for our usage of patch_directory in wrap files. Note that
it affects only wrapdb project itself, not subprojects that can still
require older meson version.
> Set minimum meson version to 0.55.0

- releases.json
- subprojects/unit-system.wrap
I know the initial pull request to add 0.5.0 was approved just now.
However in parallel to getting that one merged there have been two
point releases. These contain some compatibility improvements and
some fixes for the build system.
Since 0.5.2 is a hotfix for 0.5.1, only 0.5.2 needs to be available
in the wrapdb.
> updating unit-system to version 0.5.2

- .github/workflows/sanity_checks.yml
- tools/sanity_checks.py
trilom/file-changes-action action has issues and it prevents running
sanity checks locally. Instead of relying on the changed files to know
which wraps are modified by a PR, rely on the added release tags.
Fixes: #121.
> sanity-checks: Make it run locally

- releases.json
- subprojects/libgpiod.wrap
- subprojects/packagefiles/libgpiod/LICENSE.build
- subprojects/packagefiles/libgpiod/bindings/cxx/examples/meson.build
- subprojects/packagefiles/libgpiod/bindings/cxx/meson.build
- subprojects/packagefiles/libgpiod/bindings/cxx/tests/meson.build
- subprojects/packagefiles/libgpiod/bindings/meson.build
- subprojects/packagefiles/libgpiod/bindings/python/meson.build
- subprojects/packagefiles/libgpiod/bindings/python/tests/meson.build
- subprojects/packagefiles/libgpiod/include/meson.build
- subprojects/packagefiles/libgpiod/lib/meson.build
- subprojects/packagefiles/libgpiod/man/meson.build
- subprojects/packagefiles/libgpiod/meson.build
- subprojects/packagefiles/libgpiod/meson_options.txt
- subprojects/packagefiles/libgpiod/tests/meson.build
- subprojects/packagefiles/libgpiod/tests/mockup/meson.build
- subprojects/packagefiles/libgpiod/tools/meson.build
The libgpiod library encapsulates the ioctl calls and data structures for accessing Linux's GPIO chardevs behind a straightforward API.
> Add libgpiod

- .github/workflows/release.yml
- .github/workflows/sanity_checks.yml
- .gitignore
- releases.json
- subprojects/openssl.wrap
- subprojects/packagefiles/openssl/LICENSE.build
- subprojects/packagefiles/openssl/README.md
- subprojects/packagefiles/openssl/generate_gypi.pl.patch
- subprojects/packagefiles/openssl/generator.sh
- subprojects/packagefiles/openssl/include/buildinf.h
- subprojects/packagefiles/openssl/include/crypto/bn_conf.h
- subprojects/packagefiles/openssl/include/crypto/dso_conf.h
- subprojects/packagefiles/openssl/meson.build
- subprojects/packagefiles/openssl/meson.build.tmpl
- subprojects/packagefiles/openssl/meson_options.txt
- tools/create_release.py
- tools/sanity_checks.py
This adds OpenSSL 1.1.1k
Important notes:
* abuses Node.js
* doesn't support ASM on Windows (there are TODOs in code if anyone cares to test)
* includes scripting for building release archive with generated files, will generate files with `meson setup` if those aren't present already
* includes readme that describes design decisions and other important details
* can build both libraries (libcrypto and libssl) and openssl executable
* tested on Linux x86-64 (Ubuntu and Alpine), macOS 11 x86-64 and Windows Server 2019 (MinWG GCC 8.1.0, Clang 12.0.1 and MSVC 19.29.30038.1 with GitHub Actions)
Fixes #109
> Add OpenSSL

- tools/sanity_checks.py
From #140
@danielcjacobs advised:
> Also, seems like there may be a bug, since it passed the sanity check just by adding [provide]. Might want it to check for the specific dependencies it's supposed to provide. Would also allow it to provide more specific error messages.
So I have, at least, made this actually be an error. Thanks for pointing this out!
...
I have also taken the opportunity while I'm there, to fix a gripe of mine and make it use better failure reporting. The test no longer aborts at the first assertion failure, but rather, keeps going in order to report all possible errors. And, it tells you which wrap the error came from.
Both of these improvements come via unittest subtests. A more thorough mechanism would probably involve using pytest parameterization across the test …
> Sanity checks improvements

- tools/sanity_checks.py
URL encoded strings have percents in them. Percents are interpolated by
ConfigParser, so use RawConfigParser to avoid the interpolation
completely.
Fixes #151
> Use the RawConfigParser to not have to escape URLs

- subprojects/catch.wrap
- subprojects/catch2.wrap
- subprojects/catchorg-clara.wrap
- subprojects/cpputest.wrap
- subprojects/cpr.wrap
- subprojects/emilk-loguru.wrap
- subprojects/google-benchmark.wrap
- subprojects/gtest.wrap
- subprojects/htslib.wrap
- subprojects/libsrtp2.wrap
- subprojects/libtiff.wrap
- subprojects/libtomcrypt.wrap
- subprojects/libwebsockets.wrap
- subprojects/microsoft-gsl.wrap
- subprojects/muellan-clipp.wrap
- subprojects/nng.wrap
- subprojects/onqtam-doctest.wrap
- subprojects/pcre2.wrap
- subprojects/protobuf.wrap
- subprojects/range-v3.wrap
- subprojects/rapidjson.wrap
- subprojects/rxcpp.wrap
- subprojects/sdl2_image.wrap
- subprojects/sdl2_net.wrap
- subprojects/sdl2_ttf.wrap
- subprojects/termbox.wrap
- subprojects/tinyply.wrap
- subprojects/trompeloeil.wrap
- subprojects/unittest-cpp.wrap
- subprojects/utfcpp.wrap
tarballs are nicer than zips, if for no other reason than they compress better. It's not a huge deal but it is slightly nicer on user bandwidth...
Making new releases for this is not necessary.
```
meson subprojects download catch catch2 catchorg-clara cpputest cpr emilk-loguru google-benchmark gtest htslib libsrtp2 microsoft-gsl muellan-clipp nng onqtam-doctest range-v3 rapidjson rxcpp termbox tinyply trompeloeil unittest-cpp utfcpp
```
before and after yields consistent savings in subprojects/packagefiles/
> update all github archives wraps to prefer using tar.gz

- .editorconfig
- README.md
- ci_config.json
- releases.json
- tools/sanity_checks.py
- tools/update-packagefiles.py
- tools/utils.py
This helps developping patch overlays, meson files can be created
directly in the right position in source tree, and this script will copy
them into packagefiles/ directory.
> Add script to update packagefiles

- ci_config.json
- tools/sanity_checks.py
Otherwise we cannot set built-in options such as `force_fallback_for`.
> CI: Do not automatically prepend subproject prefix to build options

- releases.json
- subprojects/packagefiles/xtensor/meson.build
- subprojects/packagefiles/xtensor/meson_options.txt
- subprojects/packagefiles/xtl/meson.build
- subprojects/packagefiles/xtl/meson_options.txt
- subprojects/xtensor.wrap
- subprojects/xtl.wrap
Add wraps for xtensor and xtl from the [xtensor-stack](https://github.com/xtensor-stack)
NOTE: Shows gtest commit even though this has already been merged into `wrapdb`.  Somewhat new to the whole forking process, so not sure how I should've changed my process.
> Add wraps for xtl, xtensor, and xtensor-python

- ci_config.json
- releases.json
- subprojects/rtaudio.wrap
5.2.0 is the first version with upstream meson support and was just released some days ago.
https://github.com/thestk/rtaudio
> Add RtAudio

- ci_config.json
- releases.json
- subprojects/slirp.wrap
This PR depends on the Glib 2.70.2, which is submitted under: https://github.com/mesonbuild/wrapdb/pull/241
> Add wrap files for slirp-4.6.1

- releases.json
- subprojects/tomlplusplus.wrap
Simple addition, since upstream has Meson build definition files.
> Add tomlplusplus

- releases.json
- subprojects/opencl-headers.wrap
- subprojects/packagefiles/opencl-headers/meson.build
Added OpenCLHeaders as the name as upstream uses that for its cmake
configuration files.
> opencl-headers: add

- subprojects/packagefiles/pcre2/meson.build
the reason tests on Windows were failing was because the program was running out of stack space while expanding a regex operation.
> pcre2: increase the stack size for test builds

- ci_config.json
- releases.json
- subprojects/libccp4c.wrap
- subprojects/packagefiles/libccp4c/LICENSE.build
- subprojects/packagefiles/libccp4c/meson.build
This adds a wrap for the C-language part of the [CCP4](https://www.ccp4.ac.uk/) core library.  The source code also includes a set of Fortran bindings, which are currently ignored but could be added as an optional extra if there were demand.
The license for this library is LGPL3, with liability disclaimer modified for UK law.  I've licensed my meson.build file as BSD to match the other wraps, but I'd also be happy to use LGPL3 instead with a view to eventually upstreaming the Meson file.  Note that LGPL applies only to this core library - the rest of the main CCP4 suite (which is huge), based on this library, has a proprietary licence.
The code is old (20 years, some parts older still) and there are a number of compiler warnings.  Following wrap guidelines, I haven't fixed them.  However, …
> Add wrap for libccp4c

- releases.json
- subprojects/nonstd-expected-lite.wrap
- subprojects/packagefiles/nonstd-expected-lite/meson.build
So that explicit fallbacks are not required
> nonstd-expected-lite: add overrides

- tools/sanity_checks.py
Add a simple try/catch block that allows reporting the filename of the
JSON file that failed to be decoded.  This will hopefully help folks
find the root cause of the failure faster.
> Report the filename when json decoding fails

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
- tools/sanity_checks.py
The apt cache seems sometimes outdated in docker image and installing
packages fails. Always update apt first.
Also use "apt-get" instead of "apt" in scripts to avoid warning about
unstable CI interface.
> ci: Run apt-get update to fix missing package

- .github/workflows/sanity_checks.yml
- README.md
- ci_config.json
- tools/sanity_checks.py
- tools/utils.py
This will need some fleshing out before it can get merged, which is why I am keeping as a draft for now.
Since there are now more than 2 CI options, `linux_only` no longer represents a binary choice.
Instead of adding a `<os>_only` for every single one, I suggest an array under `build_on` containing any combination of `linux`, `windows` and `darwin`.
Because up until now no one tested on MacOS, some work needs to be done to populate the `broken_darwin` array.
> add MacOS CI

- .github/workflows/release.yml
- tools/create_release.py
Fix for package missing in https://github.com/mesonbuild/wrapdb/pull/281 that led to error during release publish.
Would be nice for it to install packages from `debian_packages` automatically though.
> Fix OpenSSL CI release due to missing dependency

- ci_config.json
- subprojects/packagefiles/libmatroska/meson.build
MSVC does not support C++11. 14 is the minimum.
macOS defaults to compiling C++ as C++98. Work around this by changing
the CI config.
> libmatroska: fix compilation with MSVC and macOS

- ci_config.json
- releases.json
- subprojects/libobsd.wrap
Hi, I want to add my library to the wrapdb.
The library is like libbsd but focused on OpenBSD in specific; I wrote it primarily because I found libbsd's portability lacking and it seemed easier to rewrite it than to port the original. At the moment, it's behind libbsd on the list of functions it provides.
Beyond the automated testing in the [CI](https://github.com/guijan/libobsd/runs/5420433741), I've tested it with my [dictpw](https://github.com/guijan/dictpw) project and [scrot](https://github.com/resurrecting-open-source-projects/scrot).
> new wrap: libobsd

- ci_config.json
- releases.json
- subprojects/packagefiles/protobuf/meson.build
- subprojects/packagefiles/protobuf/src/meson.build
- subprojects/protobuf.wrap
MSVC does not support C++11. 14 is the minimum.
macOS defaults to compiling C++ as C++98. Work around this by changing
the CI config.
> protobuf: fix compilation with MSVC and macOS

- ci_config.json
- meson.build
Most C++ dependencies seem to require a newer stdlib version than is the default so let's use 17 by default to cut down on boilerplate.
> Use C++17 by default.

- releases.json
- subprojects/doctest.wrap
Update doctest to latest stable version, 2.4.8. In the meantime the project has moved from github.com/onqtam/doctest to its own org - github.com/doctest/doctest. So not sure if the wrap file should be renamed (doctest-doctest.wrap?). I don't know if there is any policy around renaming wraps.
> onqtam-doctest: Update to 2.4.8

- releases.json
- subprojects/packagefiles/ftxui/meson.build
There are no needed features used.
> ftxui: remove pointless minimum version

- tools/sanity_checks.py
Having the executed commands reported in the CI logs allows to more easily inspect the actual compiler flags used. This is especially useful when a local build environment is not available.
> ci: Run meson compile with the -v option

- subprojects/cexception.wrap
[CException](https://github.com/ThrowTheSwitch/CException) is a complementary library to the [Unity](https://github.com/ThrowTheSwitch/Unity) unit test framework, which is already [included](https://github.com/mesonbuild/wrapdb/blob/master/subprojects/unity.wrap) in wrapdb. CException has its own defined [meson.build](https://github.com/ThrowTheSwitch/CException/blob/master/meson.build) file so it should be a simple addition.
> Add CException

- ci_config.json
- releases.json
- subprojects/libwebsockets.wrap
- subprojects/packagefiles/libwebsockets/meson.build
Ran meson.build file through muon's fmt_unstable to get rid of
problematic tab usage in meson.build.
> libwebsockets: update to 4.0.21

- releases.json
- subprojects/concurrentqueue.wrap
- subprojects/packagefiles/concurrentqueue/meson.build
adds support for `concurrent queue 1.0.3` (#232 )
this library is itself a header only library
> Add concurrentqueue 1.0.3 support

- releases.json
- subprojects/glib.wrap
This is to match the pkg-config dependency name. Unfortunately the
override_dependency() was wrong in glib too, will be fixed in the next
stable release. See
https://gitlab.gnome.org/GNOME/glib/-/merge_requests/2616.
> glib: Rename gio-win32-2.0 to gio-windows-2.0

- ci_config.json
- releases.json
- subprojects/libliftoff.wrap
Depends only on libdrm, which is also available as wrap.
> libliftoff: add new wrap

- ci_config.json
- releases.json
- subprojects/cppzmq.wrap
- subprojects/packagefiles/cppzmq/meson.build
- subprojects/packagefiles/cppzmq/meson_options.txt
This currently still requires libzmq, which I will add as wrap hopefully soon.
> cppzmq: new wrap

- meson.build
> meson: update minimum version

- ci_config.json
Most Windows failures are because of symbol visibility, the CI now catch
that bug because it tries to install .lib file that does not get created
when the DLL has no public API.
> ci: Blacklist remaining failing wraps in build-all

- ci_config.json
- subprojects/packagefiles/sdl2/meson.build
- subprojects/packagefiles/sdl2/src/test/meson.build
- subprojects/packagefiles/sdl2/test/meson.build
- define a test library to be used when compiling the tests (talked about in #574)
- Fix dependencies not outwardly being defined (reported in #521)
> SDL2: fixes

- releases.json
- subprojects/freetype2.wrap
Harfbuzz lookup the freetype2 dependency like that:
```
freetype_dep = dependency(cpp.get_argument_syntax() == 'msvc' ?
'freetype' : 'freetype2', ...)
```
The reason is "freetype" is the CMake name. This causes meson to not lookup for freetype2 fallback when using MSVC.
> freetype: Provide both freetype and freetype2 names

- releases.json
- subprojects/catch2.wrap
- subprojects/packagefiles/catch2/meson.build
- subprojects/packagefiles/catch2/src/catch2/meson.build
- subprojects/packagefiles/catch2/tests/meson.build
Catch v3 now builds as a library rather than a single include file, which means that the meson.build files need to be rather more complex.
Catch v3's own CMake build system doesn't build dynamic libraries, and it doesn't seem like doing so would be worthwhile for such a project, so the Meson build only builds static libraries.
> catch2: Upgrade to v3.1.0

- tools/sanity_checks.py
It calls check_new_release() with deps=None which cause a crash.
> Fix test_build_all()

- tools/sanity_checks.py
pkg-config and cmake don't error out with Dependency not found, they have custom messages about the tool lookup. Catch these too.
Fixes #678
> sanity checks: extend pattern matching for not found dependencies

- releases.json
- subprojects/cmark-gfm.wrap
- subprojects/packagefiles/cmark-gfm/cmark-gfm-extensions_export.h.meson
- subprojects/packagefiles/cmark-gfm/cmark-gfm_export.h.meson
- subprojects/packagefiles/cmark-gfm/meson.build
Per @eli-schwartz's suggestion in https://github.com/hdoc/hdoc/pull/25, we'd like to contribute a Meson wrap for the [cmark-gfm](https://github.com/github/cmark-gfm) package.
This is a C library that implements parsing of Markdown files, and includes some extensions that GitHub (the company) has made. It's built using CMake, and this PR adds Meson support as a wrap.
> cmark-gfm: add

- tools/sanity_checks.py
Otherwise ninja won't find nasm.
> sanity_checks: Pass meson_env to compile command too

- ci_config.json
- releases.json
- subprojects/nowide.wrap
- subprojects/packagefiles/nowide/meson.build
- subprojects/packagefiles/nowide/meson_options.txt
- subprojects/packagefiles/nowide/src/meson.build
- subprojects/packagefiles/nowide/test/meson.build
- subprojects/packagefiles/nowide/test/test_iostream_interactive.py
- tools/sanity_checks.py
Hi !
This is my very first time contributing a wrap, sorry if the PR is not as polished as it could be, I'm really not that knowledgeable in build systems in general.
I'm looking for feedback on some specific points : 
**wrap name**
[nowide](https://github.com/boostorg/nowide) is apparently part of boost by default, but this wrap downloads the non-boost "standalone" variant specifically. Should it be called `nowide-standalone` then ?
**required meson version**
I have it set to `>=0.60.3` which seems a bit restrictive since I don't even know if I'm using any recent features.
**override_dependency**
To be honest I don't even really understand what this does but I saw that some of the other wraps don't use it, should I remove it ?
Thanks in advance for you help.
> Add nowide

- .github/workflows/build_all.yml
- .github/workflows/release.yml
- .github/workflows/sanity_checks.yml
Running pip directly is deprecated.
The broken pip release is no longer with msvc-dev.
> github: consistency and cleanups

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
The recent changes to `.github/workflows/` mixed some harmless/good changes together with some that aren't so great. Specifically:
- we absolutely positively want to use meson from git master in the build_all CI, because the entire point of that CI is to run regression tests against bleeding-edge future versions of Meson and catch issues before release.
- macOS is broken. It's broken on multiple levels, and one of them caused CI to go red, but the real solution is the same one I PR'ed to the Meson repository, which includes a more thorough fix. I probably forgot to sync that over.
> Roll back some CI changes

- .github/workflows/build_all.yml
Enabling CI in forks is reasonable because people might want to enable CI in order to test commits before submitting them as PRs. It's a bit less reasonable to run a weekly job no matter what -- this is intended primarily for upstream WrapDB usage to detect and investigate regressions, and won't provide meaningful results distinct from the upstream repository if run on forks. All it does is waste time and resources.
Like mesonbuild/meson's images.yml, this also allows running even on forks, if started for a reason other than automatic scheduling. In the case of Meson, it's still interesting to test whether updates to the image generation routines work, and in the case of the WrapDB, someone might want to manually test a fork for the same reason people with write permissions to the WrapDB …
> CI: do not run scheduled jobs in forks

- subprojects/packagefiles/openssl/generator.sh
xargs has different behavior across platforms, causing some paths to be omitted from the generation. This fixes those omissions.
This is based on @eli-schwartz's proposal here: https://github.com/mesonbuild/wrapdb/issues/830#issuecomment-1356671325
> Update generator.sh to be more portable

- subprojects/packagefiles/spdlog/src/meson.build
When adding spdlog as a subproject with the default_option `compile_library=true` set while using internal fmt, build fails:
Example:
```
spdlog_proj = subproject(
'spdlog',
default_options: [
'compile_library=true'
]
)
```
Error:
```
subprojects/spdlog-1.11.0/src/meson.build:11:2: ERROR: File fmt.cpp does not exist.
```
This is because spdlog renamed `fmt.cpp` in the 1.11.0 release. This PR updates the filename to match the new spdlog path.
> spdlog: Update fmt.cpp to bundled_fmtlib_format.cpp to track 1.11.0 change

- .gitattributes
The original goal was to use utf8 for the git repo.
> git: set encoding, not working-tree-encoding

- releases.json
- subprojects/packagefiles/unittest-cpp/UnitTest++/meson.build
- subprojects/packagefiles/unittest-cpp/meson.build
- subprojects/unittest-cpp.wrap
Also silence warnings under MSVC.
> unittest-cpp: use proper check for Windows

- releases.json
- subprojects/packagefiles/sdl2/meson.build
- subprojects/packagefiles/sdl2/meson_options.txt
- subprojects/packagefiles/sdl2/test/meson.build
- subprojects/sdl2.wrap
This better reflects how sdl2main should be used and actually works when a library (e.g. sdl2_image) links to sdl2 in a project that builds with `with_main=true`.
Mark `with_main` deprecated and default it to false - this is a sensible default now that linking to sdl2main the right way is simple.
sdl2_test is used for testing by some other projects, e.g. sdl2_image - which motivated me to do this change in the first place.
Additionally, bump required meson version to 0.60 and replace deprecated functions with alternatives.
> sdl2: provide sdl2main and sdl2_test dependencies, don't link to sdl2main by default

- releases.json
- subprojects/bshoshany-thread-pool.wrap
- subprojects/packagefiles/bshoshany-thread-pool/meson.build
Add https://github.com/bshoshany/thread-pool - a header-only C++ thread pool implementation. I've [PRed](https://github.com/bshoshany/thread-pool/pull/106) `meson.build` upstream, so hopefully next release will include it, allowing us to only keep wrap around. Includes built-in tests.
As for wrap name, it was taken from conan and vcpkg versions of this library.
> Add bshoshany-thread-pool

- ci_config.json
- releases.json
- subprojects/glbinding.wrap
- subprojects/packagefiles/glbinding/bundled_headers/glbinding-aux/glbinding-aux_api.h
- subprojects/packagefiles/glbinding/bundled_headers/glbinding-aux/glbinding-aux_export.h
- subprojects/packagefiles/glbinding/bundled_headers/glbinding-aux/glbinding-aux_features.h
- subprojects/packagefiles/glbinding/bundled_headers/glbinding/glbinding_api.h
- subprojects/packagefiles/glbinding/bundled_headers/glbinding/glbinding_export.h
- subprojects/packagefiles/glbinding/bundled_headers/glbinding/glbinding_features.h
- subprojects/packagefiles/glbinding/meson.build
- subprojects/packagefiles/glbinding/meson_options.txt
- subprojects/packagefiles/glbinding/pch/pch.h
- subprojects/packagefiles/glbinding/source/tests/meson.build
- tools/sanity_checks.py
Add https://github.com/cginternals/glbinding - a C++ OpenGL binding/loader with enhanced type safety. Includes glbinding-aux library, which is not built by default.
Upstream relies on CMake-generated headers that are far too complex to reproduce nicely with meson, so I've bundled them and tweaked where needed.
I'm not quite sure about tests - it's an OpenGL library, so I doubt CI will manage to run them.
> Add glbinding

- releases.json
- subprojects/packagefiles/physfs/meson.build
- subprojects/packagefiles/physfs/meson_options.txt
- subprojects/physfs.wrap
Add [physfs](https://github.com/icculus/physfs) - a portable filesystem/archive access wrapper often used by games. Does not depend on anything except threads (and a bit of platform-specific stuff which is not really notable).
I've decided to disable most archivers by default, since they are pretty unlikely to be used by most applications these days, only leaving zip and 7z. However, users are free to re-enable those archivers by explicitly enabling options.
I've included a very simple test to verify that it links and runs, since `test.c` from upstream is interactive and not very portable.
> Add physfs

- releases.json
- subprojects/magic_enum.wrap
I'm also looking into improving upstream meson support to include tests and options (see https://github.com/Neargye/magic_enum/pull/255).
> magic_enum: update to 0.8.2

- releases.json
- subprojects/liburing.wrap
- subprojects/packagefiles/liburing/src/meson.build
```
The pkg-config name of liburing is "liburing", so ideally it would be
possible to use just
dependency('liburing')
to find either the system provided liburing or fall back to the subproject.
However, that does not work since the liburing wrap project does not
override or provide the "liburing" dependency name, so one has to use
dependency('liburing', fallback: ['liburing', 'uring'])
or
dependency('liburing', 'uring')
This change makes it possible to use
dependency('liburing')
with both system (pkg-config) and the wrapdb provided liburing.
```
> liburing: override "liburing" dependency name

- releases.json
- subprojects/packagefiles/robin-map/meson.build
- subprojects/robin-map.wrap
Added [robin-map](https://github.com/Tessil/robin-map). 
**Note**: `robin-map` is a dependency of [nanobind](https://github.com/wjakob/nanobind). I plan on adding a wrap for nanobind as well.
> Add robin-map

- releases.json
- subprojects/liburing.wrap
- subprojects/packagefiles/liburing/src/meson.build
The upstream project ships a pkg-confing file with the "liburing" name, so use that.
> liburing: drop "uring" dependency name

- releases.json
This fixes the indentation for c-flags.
Before its version and dependency_names had an indent of 4 now they have one of 2 like the rest.
The only reason for this is to allow automatic updates of the releases file since every formatter requires consistent indentation (or at least they will produce them when writing).
In other words this pr is to prevent changes accidental changes to the releases file in the future.
> fixing indent for c-flags

- releases.json
- subprojects/irepeat.wrap
Native meson build. Release archive v0.6 created for this wrap.
Updated IREPEAT to use lowercase project and dependency names
as wrapDB appeared to require that change.
> Add IREPEAT wrap

- ci_config.json
- releases.json
- subprojects/cairo.wrap
- subprojects/fontconfig.wrap
- subprojects/fribidi.wrap
- subprojects/pixman.wrap
This also add support for disabling cairo tests (see https://github.com/mesonbuild/wrapdb/pull/366#issuecomment-1235580822) and increase test timeout for pixman.
> Add cairo, fontconfig, fribidi and pixman

- releases.json
- subprojects/minizip-ng.wrap
- subprojects/packagefiles/minizip-ng/include-workaround-meson/minizip/meson.build
- subprojects/packagefiles/minizip-ng/meson.build
- subprojects/packagefiles/minizip-ng/test/meson.build
While the proper thing to do is to include the headers without a minizip prefix, there are projects out there that do such a thing and compilation succeeds because of /usr/include being default.
Also rework crypt_dep to match on OS first. No point in a heavy dependency like OpenSSL.
> minizip-ng: add include-workaround-meson

- releases.json
- subprojects/opencl-headers.wrap
- subprojects/packagefiles/opencl-headers/meson.build
- subprojects/packagefiles/opencl-headers/tests/meson.build
Update dependency name to match pkgconfig. Also the version.
Various other cleanups.
> opencl-headers: update to 2023.04.17

- subprojects/packagefiles/lua/meson.build
`-DLUA_BUILD_AS_DLL` was being applied to all non-POSIX platforms rather than only Windows, this would lead to `__declspec(dllexport)`/`__declspec(dllimport)` being used which is Windows-specific causing compilation to fail on non-Windows platforms.
> lua: Only build as DLL on Windows

- ci_config.json
- releases.json
- subprojects/giflib.wrap
- subprojects/packagefiles/giflib/meson.build
- subprojects/packagefiles/giflib/meson_options.txt
Note: there's an unnecessary include of `unistd.h` in `gif_hash.h` that breaks the MSVC build, so I had to include a patched one… There hasn't been any activity on the upstream repository since the last release (4 years ago), so I don't think a fix is forthcoming.
> giflib: add version 5.2.1

- tools/sanity_checks.py
Rational: speedup installs by selecting only what's strictly necessary.
> sanity checks: don't install recommended APT packages

- ci_config.json
- releases.json
- subprojects/curl.wrap
- subprojects/packagefiles/curl/lib/meson.build
- subprojects/packagefiles/curl/meson.build
- subprojects/packagefiles/curl/meson/curl_config.h.meson
- subprojects/packagefiles/curl/meson/extract.mk
- subprojects/packagefiles/curl/meson/rewrite.mk
- subprojects/packagefiles/curl/meson_options.txt
- subprojects/packagefiles/curl/src/meson.build
- subprojects/packagefiles/curl/tests/libtest/.libs/meson.build
- subprojects/packagefiles/curl/tests/libtest/meson.build
- subprojects/packagefiles/curl/tests/log/meson.build
- subprojects/packagefiles/curl/tests/meson.build
- subprojects/packagefiles/curl/tests/server/meson.build
- subprojects/packagefiles/curl/tests/unit/meson.build
- tools/sanity_checks.py
Note:
- not the latest version (8.0.1 is from 2023, latest is 8.2.1 released July 2023), because that's what I started with.
- advanced / experimental options are not supported: Unicode (Windows), HTTP/3, Hyper HTTP backend, WebSocket…
- not all SSL backends are supported: only OpenSSL, Secure Channel (Windows), and Secure Transport (Windows)
- not all LDAP providers are supported: only OpenLDAP `>= 2.4.48` (2019) and Windows.
Close #561.
> curl: add 8.0.1

- releases.json
- subprojects/libsass.wrap
- subprojects/packagefiles/libsass/include/meson.build
- subprojects/packagefiles/libsass/meson.build
- subprojects/packagefiles/libsass/src/meson.build
This is a direct copy of https://github.com/lazka/libsass/tree/meson which I've created for gtk back in the days.
There is an open PR for adding meson support upstream in https://github.com/sass/libsass/pull/3073 but the project is considered deprecated and hasn't seen a commit in over a year, so there is not much hope for progress there.
There is a newer 3.6.5 release out, but I wanted to copy things as is from my fork first and look at updating it later.
> Add libsass 3.6.4

- .github/workflows/sanity_checks.yml
Rational: the failure modes are not always the same, and you end up wasting more CI resources if you need to trigger multiple builds because you were not aware of different issues.
> ci: disable `fail-fast` option on MSYS2 matrix jobs

- ci_config.json
- releases.json
- subprojects/freeglut.wrap
- subprojects/packagefiles/freeglut/meson.build
- subprojects/packagefiles/freeglut/meson_options.txt
I created this wrap-file for the mesa-demos repository, and I figured others might be interested in this.
A few details:
1. We provide both "freeglut" and "glut" dependencies. This is because FreeGLUT has it's own API that is an extension of the normal GLUT API.
2. We do a few things differently from the upstream CMake build system, to make things a bit more straight-forward to use. 
- We disable the `FREEGLUT_LIB_PRAGMAS` option unconditionally. We don't need it, as meson is perfectly capable to forward the correct linker args without it.
- We don't try to match the libnames. This is really only needed for the `FREEGLUT_LIB_PRAGMAS` option, which we already disable.
- No GLES support. I have some untested patches for this, but would prefer to land GL only for now.
- No Blackberry OS …
> add freeglut wrap

- releases.json
- subprojects/packagefiles/sassc/meson.build
- subprojects/sassc.wrap
This is a direct copy of https://github.com/lazka/sassc/tree/meson which I've created for gtk back in the days.
This project is in a similar situation as #1153. There exists an upstream PR for adding meson (https://github.com/sass/sassc/pull/269), but the project is unmaintained, so unlikely to see progress there.
> Add sassc 3.6.2

- ci_config.json
- releases.json
- subprojects/packagefiles/sqlitecpp/meson.build
- subprojects/sqlitecpp.wrap
adds [SQLiteCpp](https://github.com/SRombauts/SQLiteCpp) version 3.3.1 to the list of wraps
If there is anything else required just let me know
> a previous PR for this wrap was in #816
> add sqlitecpp 3.3.1-1

- releases.json
- subprojects/proxy-libintl.wrap
This is a dependency of GLib and can be used as fallback for gettext on
all platforms.
> Add proxy-libintl wrap

- .github/workflows/build_all.yml
- .github/workflows/release.yml
- .github/workflows/sanity_checks.yml
Bot to update CI.
This will update at least actions/checkout on merge.
> github: add dependabot

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
The `wrapdb` user need to be allowed to run sudo without a password for `sanity_checks.py` to be able to install additional packages.
> ci: fix `sanity_checks.py` package installs on alpine

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
Cf. https://github.com/benoit-pierre/wrapdb/actions/runs/7993113654/job/21828196022#step:5:18
```
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try brew install
xyz, where xyz is the package you are trying to
install.
If you wish to install a non-brew-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip.
If you wish to install a non-brew packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, …
```
> ci: fix meson installs for macOS workflows

- releases.json
- subprojects/packagefiles/type_safe/meson.build
- subprojects/packagefiles/type_safe/meson_options.txt
- subprojects/type_safe.wrap
Project can be found [here.](https://github.com/foonathan/type_safe)
I'm not super happy about adding the `/Wd4800` for MSVC, but that's something
I will look into doing something about. (read: fixing the code so it doesn't
warn on that in the first place.)
Depends on debug\_assert (PR #1419).
> type_safe: new wrap

- ci_config.json
- releases.json
- subprojects/packagefiles/x-plane-sdk/meson.build
- subprojects/packagefiles/x-plane-sdk/meson_options.txt
- subprojects/x-plane-sdk.wrap
- tools/sanity_checks.py
Packaging up the [X-Plane plugin SDK](https://developer.x-plane.com/sdk/plugin-sdk-downloads/) for easy use with Meson.
> x-plane-sdk: new wrap

- ci_config.json
- releases.json
- subprojects/nativefiledialog-extended.wrap
- subprojects/packagefiles/nativefiledialog-extended/meson.build
- subprojects/packagefiles/nativefiledialog-extended/meson_options.txt
- subprojects/packagefiles/nativefiledialog-extended/src/meson.build
- subprojects/packagefiles/nativefiledialog-extended/test/meson.build
This is a wrap for this project: [nativefiledialog-extended](https://github.com/btzy/nativefiledialog-extended/)
the tests are disabled by default, since they require a display system and user interaction, but where tested locally
> add new wrap: nativefiledialog-extended

- releases.json
- subprojects/packagefiles/nativefiledialog-extended/src/meson.build
fix previously untested scenarios:
- shared library on windows
- flatpak build (with portal)
- installation in general
> nativefiledialog-extended: fix previously untested scenarios

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
The `macos-latest` runner image has historically been x86_64, but it's [currently migrating](https://github.blog/changelog/2024-04-01-macos-14-sonoma-is-generally-available-and-the-latest-macos-runner-image/) from `macos-12` to `macos-14` which [runs on arm64 hardware](https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/).  It seems useful to get test coverage on both architectures, so arrange that for now.  Presumably we'll eventually have to drop macOS x86_64 tests when the `macos-12` image goes out of support.
Homebrew installs into `/opt/homebrew` on arm64 Macs.
> ci: run macOS builds on both arm64 and x86_64

- ci_config.json
glib 2.80+ build-requires the Python `packaging` package, which isn't preinstalled in the MSYS runners.
> glib: install Python `packaging` package in MSYS CI

- .github/workflows/sanity_checks.yml
A failure to build on `arm64` does not necessarily mean `x86_64` will fail too, and vice versa, so it's useful to try to run both jobs to completion. Case in point: it looks like the openssl install on `arm64` is borked (see #1466 and #1492).
> ci: disable `fail-fast` option on macOS matrix jobs

- releases.json
- subprojects/google-benchmark.wrap
- subprojects/packagefiles/google-benchmark/meson.build
- subprojects/packagefiles/google-benchmark/meson_options.txt
- subprojects/packagefiles/google-benchmark/test/meson.build
Compared to 1.7.1-2, this
- Additionally provides 'benchmark-main' which includes the provided `main()`
- Adds the option 'tests' to disable tests (Closes #1311)
- Adds more of the tests
> google-benchmark: update to 1.8.3

- ci_config.json
- releases.json
- subprojects/nanoarrow.wrap
> nanoarrow: Add new package

- releases.json
Reformat `releases.json` with `json.dump(..., indent=2, sort_keys=True)`.
Broken out of an upcoming automation PR which will likely require extended discussion.
> `releases.json` formatting cleanups

- .github/workflows/sanity_checks.yml
Rational: the failure modes are not always the same, and you end up wasting more CI resources if you need to trigger multiple builds because you were not aware of different issues.
> ci: disable `fail-fast` option on VisualStudio matrix jobs

- .github/workflows/autoupdate.yml
- tools/versions.py
Use upstream release data from Anitya ([release-monitoring.org](https://release-monitoring.org/)).  Anitya has a database of known software projects, a polling mechanism for identifying new releases, and a mechanism to map downstream package names to Anitya-tracked projects.
I've [populated Anitya](https://release-monitoring.org/distro/Meson%20WrapDB/) with WrapDB package names (click the names in the package name column), manually verifying in each case that the Anitya project matches the software actually shipped in WrapDB.  In cases where Anitya doesn't know about a project, I have mostly not added a new record, and am not sure whether or not we should add records in all such cases.
With Anitya populated, we can query a single HTTPS endpoint to get the current versions of all our …
> Add tool to check for new upstream versions and autoupdate if possible

- releases.json
- subprojects/packagefiles/zpp_bits/include/meson.build
- subprojects/packagefiles/zpp_bits/meson.build
- subprojects/zpp_bits.wrap
I'm not sure if meson_version: '>=1.0.1' should be so high but this is the one i'm using right now
> zpp_bits: Add new wrap 4.4.23

- ci_config.json
- releases.json
- subprojects/libpfm.wrap
- subprojects/packagefiles/libpfm/examples/meson.build
- subprojects/packagefiles/libpfm/include/meson.build
- subprojects/packagefiles/libpfm/lib/meson.build
- subprojects/packagefiles/libpfm/meson.build
- subprojects/packagefiles/libpfm/perf_examples/meson.build
- subprojects/packagefiles/libpfm/perf_examples/x86/meson.build
- subprojects/packagefiles/libpfm/tests/meson.build
Libpfm is unique in that building for ARM only works when also building for Linux. This causes the build to fail for MacOS arm64 in CI. ~~https://github.com/mesonbuild/wrapdb/pull/1597 adds the logic necessary to handle this situation.~~
**EDIT:** To work around the above issue without changes to the CI, this wrap is designed to only support Linux. Attempts to use it on other platforms will result in an error.
> Add libpfm

- ci_config.json
- releases.json
- subprojects/packagefiles/pegtl/meson.build
- subprojects/packagefiles/pegtl/meson.options
- subprojects/packagefiles/pegtl/src/example/pegtl/meson.build
- subprojects/packagefiles/pegtl/src/test/pegtl/meson.build
- subprojects/pegtl.wrap
This is a header only library, so nothing special, the rest is taken from their CMake build definitions (example and test build setup)
Per default tests and examples are only built, if NOT in a subproject, but since the CI executes this as a subproject, I enabled those two there.
> add new wrap: "pegtl"

- ci_config.json
- releases.json
- subprojects/nanobind.wrap
- subprojects/packagefiles/nanobind/meson.build
> Add nanobind

- .github/workflows/sanity_checks.yml
- ci_config.json
- tools/sanity_checks.py
In preparation for Homebrew disabling `python-packaging`:
> python-packaging has been deprecated! It will be disabled on 2024-10-05.
Cf. https://github.com/Homebrew/homebrew-core/issues/157500
> sanity_checks: add support for installing Python packages

- ci_config.json
Wayland 1.23.1 [fixes the warning](https://gitlab.freedesktop.org/wayland/wayland/-/commit/cc34a7a4f1d720498ef2b3b62a113d818d4141a7) that this option suppressed in the past.
> Stop disabling fatal warnings for Wayland

- tools/versions.py
- Add short subcommand aliases: `au` for `autoupdate`, `ls` for `list`
- Add `autoupdate -p|--port` option to update ports (wraps with downstream packagefiles).  The packagefiles will need manual changes, so don't allow this by default, but it's useful to provide a command for automatically handling the `<port>.wrap` and `releases.json` portions of the update.
- Add `autoupdate -r|--revision` option to update the revision number of an otherwise-current port, since it's a common operation that's trivial to automate.
> tools/versions: quality-of-life improvements

- releases.json
- subprojects/concurrentqueue.wrap
- subprojects/packagefiles/concurrentqueue/meson.build
> concurrentqueue: update to 1.0.4

- tools/versions.py
Some projects use tag or tarball names with dashes or underscores as the version component separator.
> tools/versions: update URLs with dashed or underscored version

- releases.json
- subprojects/packagefiles/zlib-ng/LICENSE.build
- subprojects/packagefiles/zlib-ng/get-version.py
- subprojects/packagefiles/zlib-ng/meson.build
- subprojects/packagefiles/zlib-ng/meson_options.txt
- subprojects/packagefiles/zlib-ng/process-zconf.py
- subprojects/packagefiles/zlib-ng/test/meson.build
- subprojects/zlib-ng.wrap
- tools/sanity_checks.py
Based on `zlib.wrap` and zlib-ng's CMake build.
The wrap omits these upstream features:
- Support for building without optimizations (`WITH_OPTIM=OFF`), with `-march=native` (`WITH_NATIVE_INSTRUCTIONS=ON`), without new strategies, without runtime CPU detection, or with reduced memory requirements
- Support for building as C99
- Configurable API function name prefix
- Forcible override of optimization levels greater than 2, enablement of `-fno-semantic-interposition`, and use of software floating point on 32-bit ARM.  It's not the build system's job to override the user's settings.  We do forcibly disable LTO to prevent it potentially merging blocks built for different CPU subarches.  (GCC, at least, won't do that in any case.)
- Defining `HAVE_SYMVER` (optional, and currently a no-op)
- …
> zlib-ng: add

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
12 is deprecated and it seems Homebrew removed bottles, forcing compilation of everything, slowing CI down massively.
> CI: use macos-latest

- .github/workflows/sanity_checks.yml
It seems on update of ubuntu latest to ubuntu 24.04, it broke Alpine.
> Downgrade Ubuntu for Alpine

- tools/create_release.py
- tools/fake_tty.py
- tools/import-wraps.py
- tools/sanity_checks.py
Done with find tools -name "*.py" -exec flynt -tc -tj -a '{}' \;
> tools: convert strings to f strings

- .github/workflows/sanity_checks.yml
clang++ gets used as g++ is missing whereas gcc is present. Just override.
> CI: Alpine: Be explicit about clang

- .github/workflows/sanity_checks.yml
If there's a common-mode failure, `fail-fast: false` wastes CI resources, since emulated builds may take significant time.  However, if failures are specific to particular architectures, it's useful to know that.
`jirutka/setup-alpine@v1.3.0` fixes compatibility with Ubuntu 24.04.
> CI: Alpine: Don't fail all jobs if one fails; run containers on Ubuntu 24.04

- ci_config.json
`str.format()` is fixed now, but the released version of proxy-libintl still generates a Meson warning.
> glib: update reason for disabling fatal warnings

- ci_config.json
- releases.json
- subprojects/mpark-patterns.wrap
- subprojects/packagefiles/mpark-patterns/meson.build
- subprojects/packagefiles/mpark-patterns/meson.options
- subprojects/packagefiles/mpark-patterns/test/meson.build
Sorry for the noise, it should work now...
> Add wrap files for mpark-patterns-0.3.0

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
Until now, we've only tested aarch64 on macOS.
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
> CI: add Ubuntu aarch64

- .github/workflows/sanity_checks.yml
`github.head_ref` is only defined for pull requests, not for pushes, so pushes to different branches within a repo would cancel each other's CI runs.  That wouldn't have affected mesonbuild/wrapdb, but in forked repos it made it hard to test multiple branches at once without creating PRs. Switch to `github.ref`, which has the desired semantics and is valid for both pull requests and pushes.
> CI: Don't cancel sanity checks upon push to a different branch

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
ff119ca60184 dropped Alpine sanity checks on x86_64 and did not add aarch64.  Both architectures are tested elsewhere, but it's useful to be able to do side-by-side comparisons if a build fails only on some arches.  Add x86_64 and aarch64 to Alpine sanity checks.
Use aarch64 runners for non-x86 Alpine.  They can run aarch64 natively (and also armv7 when setup-alpine supports it), and also execute CPU emulation faster than the x86_64 runners.
Add Alpine aarch64 to `build_all` workflow.
> CI: Alpine improvements

- .github/workflows/sanity_checks.yml
Allow one Ubuntu job to run to completion if the other fails, as we do for the other job types.
> CI: disable `fail-fast` for Ubuntu sanity check jobs

- ci_config.json
- releases.json
- subprojects/blueprint-compiler.wrap
I was not able to get a single CI job to pass before I gave up and disabled tests.  Even on platforms where I got the entire dependency chain installed, tests were segfaulting.
> blueprint-compiler: update to 0.16.0

- .github/workflows/sanity_checks.yml
Until setup-alpine supports this directly, we can undo its binfmt_misc configuration so builds run natively.
> CI: Run Alpine armv7 job on aarch64 without CPU emulation

- ci_config.json
- releases.json
- subprojects/libaegis.wrap
- subprojects/packagefiles/libaegis/meson.build
This adds a wrap for libaegis, from https://github.com/aegis-aead/libaegis:
> Portable C implementations of the [AEGIS](https://datatracker.ietf.org/doc/draft-irtf-cfrg-aegis-aead/) family of high-performance authenticated ciphers (AEGIS-128L, AEGIS-128X2, AEGIS-128X4, AEGIS-256, AEGIS-256X2, AEGIS-256X4), with runtime CPU detection.
Which is basically AES-GCM but 5x faster than even openssl's implementation.
> Add libaegis-0.4.0 to wrapdb

- tools/sanity_checks.py
Otherwise they'll use the wrong formatting rules.
> sanity_checks: instruct users to run meson format with `-c meson.format`

- ci_config.json
- releases.json
- subprojects/packagefiles/win-iconv/meson.build
- subprojects/packagefiles/win-iconv/meson_options.txt
- subprojects/win-iconv.wrap
See https://github.com/mesonbuild/wrapdb/pull/2044#issuecomment-2802862225 😄 
The latest release is quite old, the diff between then and now has a few changes :(
[see here](https://github.com/win-iconv/win-iconv/compare/v0.0.8...master)
(ref https://github.com/win-iconv/win-iconv/issues/43)
Edit: 0.0.9 released, I will add that later, once this PR is merged
Note: after this PR we can remove all occurrences of `libxml2:iconv=disabled` in the ci_config, as `iconv` can be found on Windows.
~~Question: Why is the ci_config settings not working? Why are non-windows ci jobs not skipped?~~
I should just read the entire log 🤦🏼‍♂️
> add win-iconv wrap

- .github/workflows/sanity_checks.yml
We already weren't running sanity checks on new tags in `mesonbuild/wrapdb` because the tags are created automatically by a workflow, so GitHub's recursion avoidance doesn't start the checks.  However, when manually testing changes in a fork, it's necessary to keep the fork's tags up-to-date to prevent sanity checks from testing all untagged wrap updates, but pushing tags to the fork would start CI on each of them.
Avoid this by running sanity checks only on pull requests and branch pushes.  This change only affects new tags created after this commit, not older tags which are later pushed to a fork.
> CI: don't run sanity checks when tags are pushed

- ci_config.json
- tools/sanity_checks.py
New Meson releases sometimes add dubious warnings that break existing packages built with `--fatal-meson-warnings`, which is the WrapDB default. Add a mechanism to detect when setup fails on a warning that matches a regex and automatically rerun setup without `--fatal-meson-warnings`.  This is a large hammer, but allows us to continue making forward progress in this repo while fixes percolate into Meson.
For now, match the new warning in 1.7.1+ that triggers if CMake is used to detect a dependency when the `Find*.cmake` file is shipped with CMake itself and the dependency is not available.  This shouldn't be fatal, and in fact it triggers even for optional dependencies.
> sanity_checks: auto-disable fatal warnings if CMake warning is in logs

- tools/sanity_checks.py
The problem is fixed in Meson 1.8.0.
Leave the auto-rerun logic in place, since we may need it again.
> sanity_checks: stop auto-disabling warnings if CMake doesn't find a dep

- tools/versions.py
Add a convenience subcommand to convert libtool `current:revision:age` into a conventional version number.
> tools/versions: add subcommand to translate libtool version-info

- tools/sanity_checks.py
`test_releases_json` validates that all existing tags are mentioned in `releases.json`.  This ensures PRs don't mangle or remove old `releases.json` entries, but poses the potential for races in CI.  We don't want PR CI to fail because of a newly-created tag the PR branch doesn't know about.
If a PR is created from a stale branch, this doesn't cause a problem. `actions/checkout` checks out a synthetic merge commit against the current master branch, so the `releases.json` seen by `sanity_checks.py` includes any newly-tagged versions even if the PR branch does not.  Likewise, if a tag is created after `actions/checkout` runs, the CI job doesn't see the new tag, so there's no problem.
However, if a tag is created *after* the synthetic merge commit but *before* a job runs `actions/checkout`, …
> sanity_checks: in PR CI, avoid tag check racing with tag creation

- meson.build
I'm not sure if it's wright, sanity checks passes - original commit that added this variable was later removed https://github.com/mesonbuild/wrapdb/commit/db21541a5afcaa5daed94c3264c1b12fc4eeb37d
> Remove unnecessary subproject variables inside meson.build

- tools/versions.py
For version bumps, autogenerate the commit message.  For other wrap changes, require a manually-specified commit message but prepend the wrap name.  (Less useful, but perhaps has some value.)  In all cases, commit only those files that might be relevant.
> tools/versions: add command to commit wrap changes with automatic log

- releases.json
- subprojects/gflags.wrap
- subprojects/packagefiles/gflags/meson.build
- subprojects/packagefiles/gflags/src/gflags/meson.build
- subprojects/packagefiles/gflags/src/meson.build
This is a pre-cursor to add support for Apache Arrow in https://github.com/mesonbuild/wrapdb/pull/2099
> gflags: Add new wrap

- releases.json
- subprojects/backward-cpp.wrap
- subprojects/packagefiles/backward-cpp/meson.build
backward-cpp distributes a a header-only library in addition to the module. The header-only library can be useful as a standalone dependency, especially on systems where the module may be difficult to compile (i.e. Windows)
https://github.com/bombela/backward-cpp?tab=readme-ov-file#installation
> backward: Add dependency to just grab header

- subprojects/packagefiles/cmocka/meson.build
Remove the variable `cfile` because it is unused.
> cmocka: remove unused variable

- .github/workflows/sanity_checks.yml
- tools/sanity_checks.py
WrapDB includes a lot of projects with missing license declarations or invalid SPDX expressions.  Projects with upstream Meson configs have a longer fix cycle, so it'd be too painful to fail CI on invalid licenses, but for downstream Meson configs we can certainly require fixes when wraps are updated.
`meson-info` doesn't mention the licenses of subprojects, but we can extract that information from the rewriter, if it is working.  (Extraction fails if the Meson requests a compiler that isn't installed.)
Use the [license-expression](https://pypi.org/project/license-expression/) library, if installed, to validate the SPDX expression.  Install it in every sanity-check job since we don't know which jobs will successfully run the rewriter.
Of course, CI can't force the license declaration to …
> Require valid license declaration for updated projects in this repo

- tools/sanity_checks.py
Upstream has a custom error message for this.  Add it to the detection list.
> wayland-protocols: avoid CI failures for unsupported platforms

- releases.json
- subprojects/boost-mp11.wrap
- subprojects/packagefiles/boost-mp11/meson.build
https://github.com/boostorg/mp11
This is a header-only, standalone Boost library that does not have any other Boost dependencies.
> boost-mp11: new wrap

- tools/sanity_checks.py
Meson < 1.8 ignores `buildtype`, `debug`, `optimization`, and a number of other options when in subproject `default_options`.  Forbid these from `default_options` since they create differential behavior across Meson versions; also it's not clear that wraps should have opinions on their values.
For https://github.com/mesonbuild/wrapdb/issues/2208.
> sanity_checks: forbid `default_options` Meson < 1.8 ignores in subprojects

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
- tools/sanity_checks.py
The annotations appear on the workflow summary screen and look like this by default:
and expanded:
Also, avoid spurious Homebrew annotations:
> ci: report any `ci_config.json` stanzas as workflow annotations

- .github/workflows/sanity_checks.yml
- tools/sanity_checks.py
After sanity checks run, put `meson_version: '>=0'` into the `project()` call of any updated downstream wrap, rerun `meson setup`, collect the new-feature warnings, and add them to an annotation on the `meson_version` argument (or on `project()` if none).  Make the annotation a notice if the Meson dependency matches what we expect and a warning otherwise.  Also explicitly check for `c_std` or `cpp_std` in `default_options`, which requires Meson &ge; 0.63.
To avoid duplicate annotations we can only do this in one CI job, so pick Ubuntu x86_64.  That platform should be compatible with most wraps; only two have `"linux": false` in `ci_config.json`.
Don't fail CI if the Meson dependency doesn't match or if the check fails. Failures can occur due to rewriter limitations, and a wrap might need …
> ci: determine minimum Meson version and annotate diff

- tools/sanity_checks.py
Don't annotate the `meson_version` as a warning just because the version request is missing a trailing `.0`.
If we don't find any versioned features, report the minimum version as `0.0.0` so we don't have to special-case the canonicalization.  We'll still accept `>=0` in `meson.build`.
> sanity_checks: treat meson_version '>=0.N' as '>=0.N.0'

- .github/workflows/sanity_checks.yml
- .gitignore
- meson.build
- subprojects/.gitignore
- tools/sanity_checks.py
On Meson versions affected (or expected to be affected) by mesonbuild/meson#14939, add C and C++ languages to the root project so subprojects will respect `c_std` and `cpp_std`.
We can adjust the version range if needed once the bug is fixed.  There's probably some value in continuing to carry this check for a while after the fix is released, since developers might have older Meson versions on their machines.
Also remove obsolete Strawberry Perl workaround and ignore `subprojects/.wraplock`.
> Work around Meson bug ignoring `c_std`/`cpp_std` in subprojects; other 1.9.0rc updates

- ci_config.json
- releases.json
- subprojects/apache-orc.wrap
Meson support for Apache ORC was implemented in https://github.com/apache/orc/pull/2249 . We will have to wait for the next release to make this official, but I figured its worth testing a wrap entry anyway, in case any issues need to be patched before the next release
FYI @dongjoon-hyun
> Add Apache ORC wrap

- tools/update-packagefiles.py
Update the `tools/update-packagefiles.py` script to ignore ` .meson-subproject-wrap-hash` files.
> tools/update-packagefiles: Don't copy .meson-subproject-wrap-hash

- ci_config.json
- releases.json
- subprojects/arrow-cpp.wrap
- subprojects/packagefiles/arrow-cpp/LICENSE.build
- subprojects/packagefiles/arrow-cpp/meson.build
- subprojects/packagefiles/arrow-cpp/meson.options
Work to make this more feature complete is still ongoing upstream in the Arrow repository, but I think the base dependency is usable enough to get started on a wrapdb entry
> Add Apache Arrow wrap

- .gitignore
- tools/format.py
- tools/sanity_checks.py
- tools/utils.py
Formatting rules change over time, and CI uses the latest Meson prerelease, so we should match that version on developers' systems.  If not running in CI, install Meson into a virtualenv that we update at most once per day.
> Use latest Meson prerelease for `meson format`

- ci_config.json
- tools/create_release.py
- tools/format.py
- tools/internalize_sources.py
- tools/sanity_checks.py
- tools/update-packagefiles.py
- tools/utils.py
- tools/versions.py
Consolidate I/O code for `releases.json`, `ci_config.json`, and wrap files.  For the JSON metadata, also ensure type hints are available in all the tools.
Also do some minor cleanups.
> tools: add utility code to load/save wrap files and JSON metadata

- tools/format.py
- tools/sanity_checks.py
- tools/utils.py
Have sanity_checks.py check that `releases.json` and wrap files for modified wraps are formatted, and have `format.py` format them.  We could also format `ci_config.json`, but sorting keys alphabetically would break some semantically meaningful groupings, so skip for now.
> tools: add formatting for wrap files and `releases.json`

- .github/workflows/build_all.yml
- .github/workflows/release.yml
- .github/workflows/sanity_checks.yml
The `create_release` job needs write access, but nothing else does.
> ci: restrict `GITHUB_TOKEN` to read access where possible

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
If we override the job name, we can put additional parameters in the job matrix and GitHub won't display them.  Use that to get rid of the ternaries.
Also some minor cleanups.
Broken out of #2406.
> ci: store ancillary job parameters in matrix

- tools/create_release.py
- tools/utils.py
Verify the hash of the downloaded source archive before uploading it.  If the download is truncated or upstream has changed the file, there's no point creating a corrupt mirror.
If we can't fetch from the `source_url`, try the `source_fallback_url`, since some of the wraps have one.
If we fail to download a valid source archive, finish the release without setting `source_fallback_url`.  Previously we crashed and left behind an unusable GitHub release without a wrap file, which we did not (and do not) try to fix on subsequent runs.
Also reorder `source_fallback_url` in the published wrap files to be next to the other `source_*` keys, not after `patch_*`, and clean up some places where `create_release.py` was writing temporary files to the Git workdir.
> create_release: improve source fallback handling

- tools/create_release.py
We've been creating a public release and then uploading files into it.  However, if we crash halfway through, we leave behind a Git tag and an unusable release without a wrap file, since that's the last thing to be uploaded.  Subsequent runs see the tag and don't retry.
(Also, if we enable [immutable releases](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/immutable-releases) in the future, GitHub won't allow us to upload to a published release.)
Instead, create the release in draft form, upload to it, and then publish the release.  GitHub doesn't create the tag until we publish, so newly-created tags will reflect only releases that have actually completed.
As a consequence, we now retry failed releases on subsequent runs.  However, …
> create_release: upload to draft release, then publish
