- releases.json
- subprojects/packagefiles/uthash/LICENSE.build
- subprojects/packagefiles/uthash/meson.build
- subprojects/uthash.wrap
This new repo for all wrap files is a great improvement.
I'm not sure if wrapdb accepts header-only libraries, but here we go.
> Add uthash

- releases.json
- subprojects/gtest.wrap
- subprojects/packagefiles/gtest/googlemock/meson.build
- subprojects/packagefiles/gtest/googletest/meson.build
- subprojects/packagefiles/gtest/meson.build
Encountered [bug with googletest 1.10.0](https://github.com/google/googletest/issues/2650)
Added version 1.11.0
> Add gtest version 1.11.0

- releases.json
- subprojects/frozen.wrap
- subprojects/packagefiles/frozen/LICENSE.build
- subprojects/packagefiles/frozen/meson.build
> add wrap for frozen

- tools/create_release.py
- tools/import-wraps.py
- tools/sanity_checks.py
- tools/update-packagefiles.py
Could add mypy too. The add_to_db() function is weird.
> Add typing to Python tools

- releases.json
- subprojects/lcms2.wrap
- subprojects/packagefiles/lcms2/meson.build
This is extracted from libopenjp2's thirdparty directory.
> Add lcms2 to wrapdb

- ci_config.json
- releases.json
- subprojects/wayland-protocols.wrap
These use meson upstream, and are mostly just headers.
> Add wayland-protocols

- releases.json
- subprojects/packagefiles/taglib/meson.build
- subprojects/taglib.wrap
> taglib: add

- ci_config.json
- releases.json
- subprojects/libnpupnp.wrap
- subprojects/packagefiles/libnpupnp/meson.build
- subprojects/packagefiles/libnpupnp/meson_options.txt
> libnpupnp: add

- releases.json
- subprojects/argparse.wrap
- subprojects/packagefiles/argparse/meson.build
Adding argparse :)
Currently does not build with clang-cl, but I have a patch submitted that should fix that and I will update it when it is merged.
> Added argparse v2.2

- releases.json
- subprojects/ff-nvcodec-headers.wrap
- subprojects/packagefiles/ff-nvcodec-headers/meson.build
- tools/sanity_checks.py
https://git.videolan.org/?p=ffmpeg/nv-codec-headers.git
> Add wrap for ff-nvcodec-headers version 11.1.5.1-0

- releases.json
- subprojects/ff-nvcodec-headers.wrap
- subprojects/packagefiles/ff-nvcodec-headers/meson.build
This reverts commit e26eaed80e4de47587aaa24d7963666fca263612.
@eli-schwartz I expect a review from you on this to tell me exactly what you would do differently.
> Revert "Revert "Add wrap for ff-nvcodec-headers version 11.1.5.1-0""

- ci_config.json
- subprojects/packagefiles/libebml/meson.build
> libebml: fix compilation with MSVC and macOS

- ci_config.json
- releases.json
- subprojects/dragonbox.wrap
- subprojects/packagefiles/dragonbox/meson.build
Added https://github.com/jk-jeon/dragonbox/
> new wrap: dragonbox

- ci_config.json
- releases.json
- subprojects/packagefiles/lmdb/libraries/liblmdb/meson.build
> lmdb: fix compilation under macOS

- meson.build
> Add a missing comma

- ci_config.json
- releases.json
- subprojects/facil.wrap
- subprojects/packagefiles/facil/meson.build
> facil: update to 0.7.6

- ci_config.json
- releases.json
- subprojects/flatbuffers.wrap
- subprojects/packagefiles/flatbuffers/meson.build
> flatbuffers: update to 2.0.6

- releases.json
- subprojects/cxxopts.wrap
- subprojects/packagefiles/cxxopts/meson.build
> cxxopts: update to 3.0.0

- ci_config.json
- releases.json
- subprojects/google-snappy.wrap
- subprojects/packagefiles/google-snappy/meson.build
> google-snappy: update to 1.1.9

- ci_config.json
- releases.json
- subprojects/hinnant-date.wrap
> hinnant-date: update to 3.0.1

- ci_config.json
- releases.json
- subprojects/packagefiles/quazip/meson.build
- subprojects/packagefiles/quazip/quazip/meson.build
- subprojects/quazip.wrap
> quazip: update to 1.3

- ci_config.json
- releases.json
- subprojects/libffmpegthumbnailer.wrap
- subprojects/packagefiles/libffmpegthumbnailer/meson.build
- subprojects/packagefiles/libffmpegthumbnailer/meson_options.txt
> libffmpegthumbnailer: add

- releases.json
- subprojects/cereal.wrap
- subprojects/packagefiles/cereal/meson.build
> cereal: update to 1.3.2

- ci_config.json
- releases.json
- subprojects/libupnp.wrap
- subprojects/packagefiles/libupnp/meson.build
- subprojects/packagefiles/libupnp/meson_options.txt
> libupnp: add

- ci_config.json
- releases.json
- subprojects/check.wrap
- subprojects/packagefiles/check/meson.build
> check: update to 0.15.2

- ci_config.json
- releases.json
- subprojects/emilk-loguru.wrap
- subprojects/packagefiles/emilk-loguru/meson.build
- subprojects/packagefiles/emilk-loguru/meson_options.txt
> emilk-loguru: try to fix for windows

- ci_config.json
- releases.json
- subprojects/glfw.wrap
- subprojects/packagefiles/glfw/examples/meson.build
- subprojects/packagefiles/glfw/meson.build
- subprojects/packagefiles/glfw/meson_options.txt
- subprojects/packagefiles/glfw/tests/meson.build
This wrap currently only works for *nix-type systems. There's enough of a base for myself or another enterprising soul to continue the project for anything not currently covered.
> GLFW v3.3.7-1

- ci_config.json
- releases.json
> cexception: add missing entry to releases.json

- releases.json
> cmock: add entry to releases.json

- releases.json
- subprojects/chipmunk.wrap
- subprojects/packagefiles/chipmunk/meson.build
> chipmunk: update to 7.0.3

- releases.json
- subprojects/bdwgc.wrap
- subprojects/packagefiles/bdwgc/meson.build
> bdwgc: update to 8.2.0

- releases.json
- subprojects/packagefiles/utf8proc/meson.build
- subprojects/packagefiles/utfcpp/meson.build
- subprojects/utfcpp.wrap
> utf8cpp: update to 3.2.1

- ci_config.json
- releases.json
- subprojects/liblastfm.wrap
> liblastfm: add

- releases.json
- subprojects/packagefiles/protobuf/meson.build
- subprojects/packagefiles/protobuf/src/meson.build
- subprojects/protobuf.wrap
Neeeded by the protobuf-c wrap.
> protobuf: update to 3.20.1

- ci_config.json
- releases.json
- subprojects/liblbfgs.wrap
- subprojects/packagefiles/liblbfgs/lib/meson.build
- subprojects/packagefiles/liblbfgs/liblbfgs.def
- tools/sanity_checks.py
> liblbfgs: fix compilation with MSVC

- ci_config.json
- releases.json
- subprojects/libusb.wrap
- subprojects/packagefiles/libusb/examples/meson.build
- subprojects/packagefiles/libusb/meson.build
- subprojects/packagefiles/libusb/meson_options.txt
- subprojects/packagefiles/libusb/tests/meson.build
> libusb: add

- releases.json
- subprojects/imguizmo.wrap
- subprojects/packagefiles/imguizmo/meson.build
An extension to ImGui
Also running sanity_checks on my fork clones and tests all the wraps not just the new one, any ideas why
> Add ImGuizo

- .github/workflows/build_all.yml
- .github/workflows/release.yml
- .github/workflows/sanity_checks.yml
- Fixes a missing required fields
- Adds concurrency
> CI updates

- ci_config.json
- releases.json
- subprojects/libxcursor.wrap
- subprojects/libxinerama.wrap
- subprojects/libxrandr.wrap
- subprojects/libxrender.wrap
- subprojects/packagefiles/libXcursor/include/X11/Xcursor/meson.build
- subprojects/packagefiles/libXcursor/meson.build
- subprojects/packagefiles/libXinerama/meson.build
- subprojects/packagefiles/libXrandr/meson.build
- subprojects/packagefiles/libXrender/meson.build
tested with
```
meson -Dwraps=glfw x
meson compile x
```
with all of these subprojects being used.
> X11 libraries

- tools/sanity_checks.py
Historically, we have a setting "linux_only" for wraps which are software that targets Linux APIs and doesn't intend to compile elsewhere. After adding more CI coverage, we changed this to "build_on" as an operating system key. The intention is that we don't need to fail CI for software that is performing within its expected parameters.
Unfortunately, this has been repeatedly misused for wraps that are currently broken and need to be fixed, which defeats the point of having CI at all. And these PRs get merged when they shouldn't be despite review objections.
Stop skipping these wraps. We should verify that they actually fail, and why. This has a couple benefits:
- if a wrap is disabled because it is missing dependencies, that's not ideal, but tolerable. Still, disabling the CI for it …
> sanity checks: verify that a wrap is actually unsupported

- ci_config.json
- releases.json
- subprojects/libxext.wrap
- subprojects/libxv.wrap
- subprojects/packagefiles/libXext/meson.build
- subprojects/packagefiles/libXv/meson.build
> libXext: add

- ci_config.json
- releases.json
- subprojects/libtirpc.wrap
- subprojects/packagefiles/libtirpc/meson.build
- subprojects/packagefiles/libtirpc/meson_options.txt
> libtirpc: add

- nginx/default
Better keep a backup of that config file here, so we can spawn a new server easily in case something happens to current host.
> Add nginx config for wrapdb.mesonbuild.com

- ci_config.json
- releases.json
- subprojects/libxxf86vm.wrap
- subprojects/packagefiles/libXxf86vm/meson.build
> libXxf86vm: add

- ci_config.json
- releases.json
- subprojects/packagefiles/tinyfsm/meson.build
- subprojects/packagefiles/tinyfsm/meson_options.txt
- subprojects/tinyfsm.wrap
for https://github.com/digint/tinyfsm
> tinysfm: add wrap

- ci_config.json
> ci_config: no pkgconfiglite

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
https://github.com/Homebrew/discussions/discussions/3895
https://github.com/actions/runner-images/issues/6507
> CI: fix macOS runners being broken

- releases.json
- subprojects/entt.wrap
- subprojects/packagefiles/entt/meson.build
This is a release of https://github.com/skypjack/entt/releases/tag/v3.11.0
Also this is my first pull request, so please tell me if I am doing something wrong.
> entt: add wrap

- ci_config.json
- releases.json
- subprojects/libdrm.wrap
> libdrm: update to 2.4.114

- ci_config.json
- releases.json
- subprojects/packagefiles/protobuf-c/meson.build
- subprojects/packagefiles/protobuf-c/protobuf-c/meson.build
- subprojects/packagefiles/protobuf-c/protoc-c/meson.build
- subprojects/protobuf-c.wrap
> protobuf-c: update to 1.4.1

- subprojects/packagefiles/pugixml/meson.build
> pugixml: fix exports under Windows

- subprojects/packagefiles/libmatroska/meson.build
> libmatroska: fix exports under Windows

- releases.json
- subprojects/packagefiles/protobuf/meson.build
- subprojects/packagefiles/protobuf/src/meson.build
- subprojects/protobuf.wrap
> protobuf: update to 3.21.9

- releases.json
- subprojects/packagefiles/websocketpp/meson.build
- subprojects/websocketpp.wrap
> Add websocketpp

- ci_config.json
- releases.json
- subprojects/unit-system.wrap
> unit-system: update to 0.5.3

- .github/workflows/build_all.yml
> github: update build_all to sanity_checks

- subprojects/zlib.wrap
Smaller. Also add fallback URL.
> zlib: use xz tarball

- releases.json
- subprojects/packagefiles/simdjson/meson.build
- subprojects/simdjson.wrap
> Add simdjson

- ci_config.json
See https://github.com/mesonbuild/wrapdb/pull/671#discussion_r987403484
> imgui: add back Debian packages for testing

- ci_config.json
- releases.json
- subprojects/c-flags.wrap
> Add c-flags

- releases.json
- subprojects/centurion.wrap
- subprojects/packagefiles/centurion/meson.build
- subprojects/packagefiles/centurion/meson_options.txt
Add https://github.com/albin-johansson/centurion - a C++ header-only wrapper for SDL2.
> Add Centurion

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
Various wraps here handle clang-cl. Test for it.
> github CI: test clang-cl

- releases.json
- subprojects/packagefiles/backward-cpp/meson.build
> backward-cpp: fix wrong machine type

- releases.json
- subprojects/bshoshany-thread-pool.wrap
- subprojects/packagefiles/bshoshany-thread-pool/meson.build
- subprojects/packagefiles/bshoshany-thread-pool/tests/meson.build
Adapt to new directory structure. Tests have been merged into a single file/executable.
> bshoshany-thread-pool: update to 3.5.0

- releases.json
- subprojects/oatpp-swagger.wrap
- subprojects/packagefiles/oatpp-swagger/meson.build
- subprojects/packagefiles/oatpp-swagger/meson_options.txt
- subprojects/packagefiles/oatpp-swagger/src/meson.build
- subprojects/packagefiles/oatpp-swagger/src/oatpp-swagger/meson.build
- subprojects/packagefiles/oatpp-swagger/test/meson.build
- subprojects/packagefiles/oatpp/meson.build
Add oatpp-swagger
The repo can be found [here](https://github.com/oatpp/oatpp-swagger)
This depends on #1039 and can only be merged after that!
> Add oatpp-swagger

- ci_config.json
- releases.json
- subprojects/oatpp-openssl.wrap
- subprojects/packagefiles/oatpp-openssl/meson.build
- subprojects/packagefiles/oatpp-openssl/meson_options.txt
- subprojects/packagefiles/oatpp-openssl/src/meson.build
- subprojects/packagefiles/oatpp-openssl/src/oatpp-openssl/meson.build
- subprojects/packagefiles/oatpp-openssl/test/meson.build
Add oatpp-openssl
The repo can be found [here](https://github.com/oatpp/oatpp-openssl)
> Add oatpp-openssl

- releases.json
- subprojects/packagefiles/stduuid/meson.build
- subprojects/packagefiles/stduuid/meson_options.txt
- subprojects/packagefiles/stduuid/test/meson.build
- subprojects/stduuid.wrap
This adds the header only library 'stduuid' from [here](https://github.com/mariusbancila/stduuid)
> add 'stduuid' wrap

- releases.json
- subprojects/packagefiles/protobuf/src/meson.build
- subprojects/protobuf.wrap
> protobuf: provide protoc program

- releases.json
- subprojects/oatpp-websocket.wrap
- subprojects/packagefiles/oatpp-websocket/meson.build
- subprojects/packagefiles/oatpp-websocket/meson_options.txt
- subprojects/packagefiles/oatpp-websocket/src/meson.build
- subprojects/packagefiles/oatpp-websocket/src/oatpp-websocket/meson.build
- subprojects/packagefiles/oatpp-websocket/test/meson.build
Add oatpp-websocket
The repo can be found [here](https://github.com/oatpp/oatpp-websocket)
> add 'oatpp-websocket'

- releases.json
- subprojects/oatpp-sqlite.wrap
- subprojects/packagefiles/oatpp-sqlite/meson.build
- subprojects/packagefiles/oatpp-sqlite/meson_options.txt
- subprojects/packagefiles/oatpp-sqlite/src/meson.build
- subprojects/packagefiles/oatpp-sqlite/src/oatpp-sqlite/meson.build
- subprojects/packagefiles/oatpp-sqlite/src/sqlite/meson.build
- subprojects/packagefiles/oatpp-sqlite/test/meson.build
Add oatpp-sqlite
The repo can be found [here](https://github.com/oatpp/oatpp-sqlite)
> Add oatpp-sqlite

- releases.json
- subprojects/croaring.wrap
- subprojects/packagefiles/croaring/meson.build
Adds a Meson build definition for [RoaringBitmap/CRoaring](https://github.com/RoaringBitmap/CRoaring), a widely used efficient bitmap impementation. 
(I have not done this before, so I don't know if this is correct, but it works in my project! 😄)
> Add CRoaring

- releases.json
- subprojects/rapidjson.wrap
> rapidjson: expose declared dependency from the wrap

- releases.json
- subprojects/packagefiles/utfcpp/meson.build
- subprojects/utfcpp.wrap
Fix dependency name to match upstream.
> utfcpp: update to 3.2.4

- ci_config.json
A rebasing issue got rid of these in the original PR.
> ci_config: MSYS2 fixes

- releases.json
- subprojects/libjpeg-turbo.wrap
I forgot to add them in #1119…
> libjpeg-turbo: fix dependency names

- .github/workflows/build_all.yml
cf. https://github.com/mesonbuild/wrapdb/pull/1123#issuecomment-1692615334.
> ci: fix transient MSYS2 failures

- ci_config.json
> tweak cURL dependent packages

- ci_config.json
- releases.json
- subprojects/jbig2dec.wrap
- subprojects/packagefiles/jbig2dec/include/meson.build
- subprojects/packagefiles/jbig2dec/meson.build
- subprojects/packagefiles/jbig2dec/meson_options.txt
- subprojects/packagefiles/jbig2dec/src/config.h.meson
- subprojects/packagefiles/jbig2dec/src/config_types.h.meson
- subprojects/packagefiles/jbig2dec/src/jbig2dec.def
- subprojects/packagefiles/jbig2dec/src/meson.build
- tools/sanity_checks.py
Upstream: https://github.com/ArtifexSoftware/jbig2dec.
> jbig2dec: add 0.20

- .github/workflows/build_all.yml
This reverts commit 2d13fcdd7c79fc2d9145ed1d8053103e1a8ed453.
> Revert "mangix: uwp"

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
- ci_config.json
- tools/sanity_checks.py
- tools/utils.py
Alpine uses musl, which makes an interesting opportunity to test packages for compilation.
Also, ninja is not used but samurai instead.
> CI: add alpine

- releases.json
- subprojects/directxmath.wrap
- subprojects/packagefiles/directxmath/meson.build
- tools/sanity_checks.py
Adding DirectXMath (header only library) wrap.
See also https://github.com/microsoft/DirectXMath
> Add DirectXMath wrap

- releases.json
- subprojects/oatpp-zlib.wrap
- subprojects/packagefiles/oatpp-zlib/meson.build
- subprojects/packagefiles/oatpp-zlib/meson_options.txt
- subprojects/packagefiles/oatpp-zlib/src/meson.build
- subprojects/packagefiles/oatpp-zlib/src/oatpp-zlib/meson.build
- subprojects/packagefiles/oatpp-zlib/test/meson.build
Add oatpp-zlib
The repo can be found [here](https://github.com/oatpp/oatpp-zlib)
> add oatpp-zlib module

- subprojects/packagefiles/openssl/generator.sh
> openssl: fix release

- ci_config.json
- releases.json
- subprojects/packagefiles/pv/meson.build
- subprojects/packagefiles/pv/meson_options.txt
- subprojects/packagefiles/pv/src/include/config.h.meson
- subprojects/packagefiles/pv/src/include/meson.build
- subprojects/packagefiles/pv/tests/meson.build
- subprojects/pv.wrap
Upstream: https://codeberg.org/a-j-wood/pv/.
> pv: add version 1.8.5

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
Newer pip doesn't like to install things normally. Reduce version for now.
> CI: reduce Alpine version

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
Simpler.
ping @jmillan @benoit-pierre 
I tested with libuv. Passes.
> CI: rework to use jirutka/setup-alpine@v1

- tools/utils.py
`1.3-5` was sorting greater than `1.3.1-1` because the normalized `[1, 3, 5]` is greater than `[1, 3, 1, 1]`.
Ensure a revision is always compared with another revision and not with a version component.  To simplify the implementation, split off the revision into a separate field of the `Version` object.  This also allows us to verify that the revision exists and is numeric.
> sanity_checks: don't compare revision against a version component

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
Cf. https://github.com/mesonbuild/wrapdb/pull/1414#issuecomment-1957853643
> ci: update alpine image to latest stable

- releases.json
- subprojects/debug_assert.wrap
- subprojects/packagefiles/debug_assert/meson.build
- subprojects/packagefiles/debug_assert/meson_options.txt
Dependency for #1418.
The macro overrides are a bit wonky, but I think I set them up right.
> debug_assert: new wrap

- releases.json
- subprojects/packagefiles/vo-aacenc/aacenc/meson.build
- subprojects/packagefiles/vo-aacenc/common/include/meson.build
- subprojects/packagefiles/vo-aacenc/common/include/stddef.h.in
- subprojects/packagefiles/vo-aacenc/common/meson.build
- subprojects/packagefiles/vo-aacenc/meson.build
- subprojects/packagefiles/vo-aacenc/meson/makedef.py
- subprojects/packagefiles/vo-aacenc/meson_options.txt
- subprojects/vo-aacenc.wrap
- tools/sanity_checks.py
👋 
This is a PR to add opencore-amr's vo-aacenc library to WrapDB. The proposed wrap was tested in https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1392.
Let me know if there are any questions.
cc @nirbheek
> Add vo-aacenc 0.1.3

- releases.json
- subprojects/packagefiles/soundtouch/include/meson.build
- subprojects/packagefiles/soundtouch/meson.build
- subprojects/packagefiles/soundtouch/meson_options.txt
- subprojects/packagefiles/soundtouch/source/Android-lib/meson.build
- subprojects/packagefiles/soundtouch/source/SoundStretch/meson.build
- subprojects/packagefiles/soundtouch/source/SoundTouch/meson.build
- subprojects/packagefiles/soundtouch/source/SoundTouchDLL/meson.build
- subprojects/packagefiles/soundtouch/source/SoundTouchDLL/meson/afxres.h
- subprojects/packagefiles/soundtouch/source/meson.build
- subprojects/soundtouch.wrap
- tools/sanity_checks.py
Hi all,
This is to upstream the wrap I made of the SoundTouch audio processing library.
See [this GStreamer MR](https://gitlab.freedesktop.org/gstreamer/cerbero/-/merge_requests/1404) for further context.
> Add soundtouch 2.3.2

- releases.json
- subprojects/cpp-semver.wrap
- subprojects/packagefiles/cpp-semver/meson.build
- subprojects/packagefiles/cpp-semver/meson.options
- subprojects/packagefiles/cpp-semver/test/meson.build
This is a header only library from [here](https://github.com/z4kn4fein/cpp-semver)
> cpp-semver: new wrap

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
- tools/fake_tty.py
- tools/sanity_checks.py
- tools/utils.py
Example workflow run: [Sanity checks](https://github.com/benoit-pierre/wrapdb/actions/runs/9198634428).
> CI improvements

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
- ci_config.json
- releases.json
- subprojects/libxkbcommon.wrap
> xkbcommon: add

- tools/sanity_checks.py
Small change to an error message nothing too crazy simply a grammatical error.
> Rewrite grammar for error

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
So building Python related stuff work.
Example: #1556.
> ci: setup a 32bits Python for the VisualStudio x32 jobs

- releases.json
- subprojects/packagefiles/sparrow/meson.build
- subprojects/packagefiles/sparrow/meson_options.txt
- subprojects/sparrow.wrap
> Add sparrow

- releases.json
- subprojects/libsigcplusplus-3.wrap
- subprojects/packagefiles/libsigcplusplus-3/meson.build
Name has the `-3` due to it being an ABI level. Tried to do `sigc++-3.0` to match the pkg-config name, but the sanity checks refuse.
> libsigcplusplus-3: init 3.6.0

- releases.json
- subprojects/cairomm.wrap
- subprojects/packagefiles/cairomm/data/meson.build
- subprojects/packagefiles/cairomm/meson.build
Patches to the Meson manifests are pending upstream.
> cairomm: init 1.18.0

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
> ci: remove debug traces and update `build_all` python for macOS

- ci_config.json
- releases.json
- subprojects/enlog.wrap
Wrap for a logging library I wrote and want to share/use elsewhere. Will be interested to see if it passes on Windows first try.
> enlog: new wrap

- releases.json
- subprojects/kraken-engine.wrap
> Add wrap files for Kraken-Engine-0.0.1

- ci_config.json
- releases.json
- subprojects/imgui-docking.wrap
- subprojects/packagefiles/imgui-docking/meson.build
- subprojects/packagefiles/imgui-docking/meson_options.txt
The commit history get really messed up with the last [PR](https://github.com/mesonbuild/wrapdb/pull/1227).
> add imgui-docking

- ci_config.json
- releases.json
- subprojects/zycore.wrap
https://github.com/zyantific/zycore-c/releases/v1.5.1
https://github.com/zyantific/zycore-c/pull/77
> zycore: new wrap

- .github/workflows/build_all.yml
- .github/workflows/sanity_checks.yml
- ci_config.json
- releases.json
- subprojects/stc.wrap
<https://github.com/stclib/STC/releases/tag/v5.0>
> stc: new wrap

- ci_config.json
- releases.json
- subprojects/miniaudio.wrap
- subprojects/packagefiles/miniaudio/examples/meson.build
- subprojects/packagefiles/miniaudio/extras/meson.build
- subprojects/packagefiles/miniaudio/extras/nodes/meson.build
- subprojects/packagefiles/miniaudio/meson.build
- subprojects/packagefiles/miniaudio/meson_options.txt
- subprojects/packagefiles/miniaudio/tests/meson.build
- subprojects/packagefiles/miniaudio/tools/meson.build
upstream: https://github.com/mackron/miniaudio/pull/936
> miniaudio: new wrap

- ci_config.json
- releases.json
- subprojects/quickjs-ng.wrap
https://github.com/quickjs-ng/quickjs/releases/v0.9.0
cc @Gottox (#1933) @trim21 (#1865) @grep0 (#1661)
> quickjs-ng: new wrap

- tools/versions.py
`--revision` currently a) refuses to bump the revision of projects with upstream Meson support or whose current version is not tracked by Anitya and b) bumps the version instead of the revision if a new version is available.  Both behaviors are based on faulty assumptions.  We might plausibly want to bump a wrap's revision after changing the wrap file, regardless of the project's status in other respects.  And it's reasonable to want to fix something in a Meson port without taking responsibility for updating it to the latest version.
Change the semantics of `--revision` to always bump the revisions of the specified wraps, even if `--port` is not specified.  If no wraps are specified, bump all wraps for consistency.
Rework the help text to describe the various things `autoupdate` can do, …
> tools/versions: always allow `autoupdate --revision`

- ci_config.json
- releases.json
- subprojects/libcap.wrap
- subprojects/packagefiles/libcap/gen_cap_names.py
- subprojects/packagefiles/libcap/meson.build
- tools/sanity_checks.py
https://sites.google.com/site/fullycapable/
> Libcap: New Wrap

- releases.json
- subprojects/mimalloc.wrap
- subprojects/packagefiles/mimalloc/meson.build
- subprojects/packagefiles/mimalloc/meson_options.txt
> mimalloc: add wrap for 3.1.5

- ci_config.json
- releases.json
- subprojects/packagefiles/sdl3_ttf/meson.build
- subprojects/packagefiles/sdl3_ttf/src/meson.build
- subprojects/sdl3_ttf.wrap
resubmitting because i moved around forks
> sdl3_ttf: add v3.2.2

- .github/workflows/sanity_checks.yml
- tools/fake_tty.py
- tools/utils.py
Switch the Ubuntu aarch64 job to Python 3.8 to prevent a recurrence.
> Fix sanity checks with Python 3.8; add CI check

- .github/workflows/build_all.yml
- .github/workflows/release.yml
- .github/workflows/sanity_checks.yml
No documented breaking changes.
> ci: bump checkout, setup-python actions for node24
